version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: goticket_rabbit
    restart: unless-stopped
    env_file: .env.backend
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"

  # ¡Nuevo contenedor de Redis añadido!
  redis:
    image: redis:alpine
    container_name: goticket_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  catalogo:
    build: ./Catalogo-Evento
    container_name: goticket_catalogo
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - SERVER_PORT=8081
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq

  inventario:
    build: ./Inventario
    container_name: goticket_inventario
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - SERVER_PORT=8082
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
      # Variables detectadas en tu application.properties
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - CATALOGO_URL=http://catalogo:8081 
    depends_on:
      - rabbitmq
      - redis
      - catalogo

  orden:
    build: ./Orden
    container_name: goticket_orden
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - SERVER_PORT=8083
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq

  pagos:
    build: ./Pagos
    container_name: goticket_pagos
    restart: unless-stopped
    env_file: .env.backend
    environment:
      - SERVER_PORT=8084
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=3306
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS}
    depends_on:
      - rabbitmq